### ISSUE TITLE
Feature request: Support more data sources

### ISSUE THREAD

**Issue by MarkusBartels** [ionos-cloud/terraform-provider-profitbricks#75]
### Terraform Version
Terraform v0.12.29
+ provider.profitbricks v1.5.4

### Affected Resource(s)
The following data sources are currently supported:
- datacenter
- image
- location
- snapshot

If there is  a lan or a crossconnect already created, we cannot source it. Modularization is problematic.

Most important:
- lan
Search for: id or name
Needed values: name, ipFailover, ppc, public

- private_crossconnect
Search for: id or name
Needed values: name, description, peers, connectableDatacenters

- server
Search for: id or name
Needed values: name, cores, ram, availabilityZone, vmState, bootCdrom, bootVolume, cpuFamily

- k8s_cluster
Search for: id or name

- k8s_node_pool
Search for: id or name

All others would be very welcome as well. Search criterium: id or name.

Searches shall be full match or part of string.

### Expected Behavior
Better support for modularization. For example:
data "profitbricks_private_crossconnect" "crossconnect" {
  name = "mycrossconnect"
}

### Actual Behavior
Not supported.

**Comment by MarkusBartels** [comment]
Added k8s_cluster and k8s_node_pool.

**Comment by LiviusP** [comment]
Hi @MarkusBartels ,

Thank you for your feedback! 
We are planning to look into this issue during the next couple of weeks. 

Best,
Livius

**Comment by tobigremmer-cg** [comment]
Hi @LiviusP ,

Would a k8s_cluster data source include the kube config?  (According to https://devops.ionos.com/api/cloud/v5/#download-config-cluster )

Best,
Tobi

**Comment by mflorin** [comment]
Hi @tobigremmer-cg ,

Most likely yes.

Best,
Florin

**Comment by mflorin** [comment]
Hello @MarkusBartels, @tobigremmer-cg,

We'd like to let you know that the `lan`, `private_cross_connect` and `server` datasources are now available in the new *1.6.0* version.

Thanks,
Florin

**Comment by mflorin** [comment]
Hello @MarkusBartels , @tobigremmer-cg,

We'd like to let you know that the `k8s_cluster` and `k8s_node_pool` are now available in the new 1.6.2 version we've released.

Thanks,
Florin
