### ISSUE TITLE
Support for Terraform 0.13

### ISSUE THREAD

**Issue by MarkusBartels** [ionos-cloud/terraform-provider-profitbricks#80]
### Terraform Version
0.12

### Expected Behavior
Terraform 0.13 shall be supported. Preferrebly the latest 0.13.3.
The need we have is the definition of the new depends_on for modules to support our modularization attempts.

### Actual Behavior
depends_on is not supported. When we utilize multiple modules the dependencies can not be modeled. E.g. if first the datacenter module must be created and then then the cluster module. Currently both modules are created at once. The creation of the cluster fails.

### Steps to Reproduce
Create a main.tf where you use two modules, which have a resource dependency.

### References
https://medium.com/hashicorp-engineering/creating-module-dependencies-in-terraform-0-13-4322702dac4a
https://github.com/hashicorp/terraform/releases/tag/v0.13.3

**Comment by LiviusP** [comment]
Hi @MarkusBartels ,

This issue as well, is planned for the next sprint. 

Livius

**Comment by MarkusBartels** [comment]
Thanks for the info. We are looking forward to this. 0.13 has some features we need.

**Comment by mflorin** [comment]
Hello @MarkusBartels,

We've tested with two modules, the first creates a datacente the second a server. The second module is dependent on the first i.e.:

```
module "datacenter" {
  source = "./datacenter"
}

module "server" {
  source = "./server"
  depends_on = [module.datacenter]
  datacenter_id = module.datacenter.id
}
```

The server module waits for the datacenter and the server is created only after the datacenter is created.
We've also tested module outputs and inputs and everything works as expected.

Please let us know if you have a scenario where things don't work for you.

Thanks,
Florin

**Comment by MarkusBartels** [comment]
@mflorin That sounds good. We can try this. I think we need to upgrade to Terraform > 0.12 for that. Which version of Terraform is supported now? Currently we use 'required_version = ">= 0.12, < 0.13"'

**Comment by mflorin** [comment]
@MarkusBartels Terraform v0.13.5 is currently supported.

**Comment by MarkusBartels** [comment]
Thanks. We are upgrading our modules.

**Comment by MarkusBartels** [comment]
Most of our module migrated. Works fine.
