### ISSUE TITLE
Feature request: MAC adress output

### ISSUE THREAD

**Issue by timrogait-ionos** [ionos-cloud/terraform-provider-profitbricks#82]
### Terraform Version
0.13.3, any

### Affected Resource(s)

- profitbricks_nic
- profitbricks_server

### Expected Behavior
MAC adress information should be profided as an output for configuration of servers and nics since this is necessary for the usage of a self deployed DHCP.

### Actual Behavior
MAC adress info is not accessible via Terraform provider.

### Important Factoids
This is highly required for a customer project.

**Comment by LiviusP** [comment]
Hi @timrogait-ionos ,

Planning this one for the next sprint. 

Best,
Livius

**Comment by mflorin** [comment]
Hello @timrogait-ionos,

Just wanted to let you know that we've just released a fix for this in version 1.6.5 of the profitbricks provider.
This fix is also available in version 5.0.4 of our new ionoscloud provider.

Thanks,
Florin
